### ISSUE TITLE
Every task as a section 🤔

### ISSUE THREAD

**Issue by leonardocardoso** [devxoul/RxTodo#10]
Why do you handle every task as a tableview section instead a section of tasks?!

[TaskListViewModel.swift#L51](https://github.com/devxoul/RxTodo/blob/2b189e76e5bc5532aefc0134dd8583e2dd1dc44a/RxTodo/Sources/ViewControllers/TaskListViewModel.swift#L51)

**Comment by devxoul** [comment]
@LeonardoCardoso, every task is handled as a row in a single section: [TaskListViewModel.swift#L59-L64](https://github.com/devxoul/RxTodo/blob/2b189e76e5bc5532aefc0134dd8583e2dd1dc44a/RxTodo/Sources/ViewControllers/TaskListViewModel.swift#L59-L64)

``` swift
self.sections = tasks.asObservable()
  .map { tasks in
    let cellModels = tasks.map(TaskCellModel.init) as [TaskCellModelType]
    let section = TaskListSection(model: Void(), items: cellModels)
    return [section] // single section
  }
```

**Comment by LeonardoCardoso** [comment]
Nvm.

**Comment by leonardocardoso** [comment]
Hey, @devxoul! Yes, this is the point! I meant a row in a section. I was just wondering why... I'm asking that because I had a real hard work converting to a `RxTableViewSectionedAnimatedDataSource` because the insertion and deletion with animation are more intuitive in this case.

I couldn't use 

``` swift
typealias TaskListSection = SectionModel<Void, TaskCellModelType>
```

I had to implement its very own class and do a lot of changes, but it worked like a charm!

**Comment by devxoul** [comment]
@LeonardoCardoso hmm I have no idea what you're talking about :( Did you mean why did I use

```
Section
  - Task
  - Task
  - Task
```

instead of

```
Section
  - Task
Section
  - Task
Section
  - Task
```

?

**Comment by leonardocardoso** [comment]
Yes. Nvm though.
