### ISSUE TITLE
Why TaskListViewModel is dealloc?

### ISSUE THREAD

**Issue by purkylin** [devxoul/RxTodo#20]
I found TaskListViewController dose not own ViewModel. The TaskListViewModel  instance will dealloc soon after TaskListViewModel has inited. Can someone explain it?

**Comment by devxoul** [comment]
Because there's no more reference to TaskListViewModel :)

**Comment by purkylin** [comment]
I wonder that binding still work as view model is dealloc.

**Comment by devxoul** [comment]
Each UI elements have the reference of the Obervables, so the oberservables won't be deinitialized. (even the owner class is deinitialized)
