### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by reejosamuel** [devxoul/RxTodo#21]
Hi, So Im following RxSwift examples. The author has mentioned to use 
```
    _ = Observable<Int>.interval(1, scheduler: MainScheduler.instance)
        .subscribe(onNext: { _ in
            print("Resource count \(RxSwift.Resources.total)")
        })
```
in the `AppDelegate` to track the resources allocation and deallocation. 

After observing the same on your RxTodo app. When you display the AddTask-ViewController and dismiss it. There is always some amount of resources which are not deallocated and the resource count keeps growing each time we open the view controller. I was wondering if you have any thoughts on fixing it. I tried adding many items to the dispose bag but doesn't seem to do the trick.

**Comment by devxoul** [comment]
Not sure but there might be memory leaks. I'm currently working on a new code base(#19) which doesn't have memory leaks at all :)

**Comment by reejosamuel** [comment]
I tried the new action-state architecture you proposed. in the todo app i don't see any leaks at all when I open and close next view controllers. But in the dribbble one with the new architecture i still see some mismatch.

With the new architecture one thing I noticed is that the cyclometric complexity of a function can increase quite a bit in a larger application because of using so many switch cases. I was thinking how we could improve so many switch cases in the `mutate` and `transform` methods but overall it seems like much more single responsibility, easier to read and functional than earlier.

**Comment by devxoul** [comment]
@reejosamuel, RxTodo is the most up-to-date code. Drrrible and Cleverbot will be updated soon :)

It's true that more enum cases can cause more complexity. But it has same complexity compare to the current architecture (Observables per each input/output). The most benefit of using enums is that compiler can validate unused/misused cases.

**Comment by seivan** [comment]
@reejosamuel Nothing prevents you from breaking down your reducer into smaller reducers.
Your enum can contain other actions. I **think** that's how Elm-lang does it and Redux has its `combineReducer()`
