### ISSUE TITLE
Mutate Action to Observable<Mutation>

### ISSUE THREAD

**Issue by vadimue** [devxoul/RxTodo#22]
Hi, @devxoul and thanks for great project. I have a question regarding TaskListViewReactor and TaskService structure. We have `func mutate(taskEvent: TaskEvent) -> Observable<Mutation>` which reacts to `var event: PublishSubject<TaskEvent> { get }` from `TaskServiceType`. 
Why should we have this variable and emit events in every method (so it is side-effect)? I see, that we subscribed in reactor and merge this event and common `Mutation`. But we can have kind of this method 
``` Swift 
private func mutateMarkIsDone(task: Task) -> Observable<Mutation> {
        return self.provider.taskService.markAsDone(taskID: task.id).flatMap { task -> Observable<Mutation> in
            let state = self.currentState
            guard let indexPath = self.indexPath(forTaskID: task.id, from: state) else { return .empty() }
            var task = state.sections[indexPath].currentState
            task.isDone = true
            let reactor = TaskCellReactor(task: task)
            return .just(.updateSectionItem(indexPath, reactor))
        }
    }
```
and remove event var from `TaskServiceType`,  remove `transform(mutation: Observable<Mutation>) -> Observable<Mutation>` and `func mutate(taskEvent: TaskEvent) -> Observable<Mutation>`. Or maybe I missed some important logic?

**Comment by devxoul** [comment]
It's because the task event should be broadcasted to all screens(ViewControllers). In RxTodo, there's no any other screen which receives the event but I hope to let developers know how to deal with global events :)

**Comment by vadimue** [comment]
Thanks for quick response, now I understood why it was needed.
