### ISSUE TITLE
edit mode : state initialisation not sync with input text 

### ISSUE THREAD

**Issue by PierreBrisorgueil** [devxoul/RxTodo#24]
Hello, 

just a little trouble I met, from the code I saw :

TaskEditViewReactor.swift
```
  init(provider: ServiceProviderType, mode: TaskEditViewMode) {
    self.provider = provider
    self.mode = mode

    switch mode {
    case .new:
      self.initialState = State(title: "New", taskTitle: "", canSubmit: false)
    case .edit(let task):
      self.initialState = State(title: "Edit", taskTitle: task.title, canSubmit: true)
      print("test 0 \(self.initialState)")
    }
  }
```
TaskEditViewController
```
    reactor.state.asObservable().map { $0.taskTitle }
      .distinctUntilChanged()
      .bind(to: self.titleInput.rx.text)
      .disposed(by: self.disposeBag)
```

I think the goal was to open the new view in edit mode with the input initiated with the text of the task to modify ?

if I understood everything, it's a bug, the input is empty in edit mode, I had the same problem on my side, I fixed it quickly by the initialization of the controller but I am sure that there is better to do.

**Comment by audrl1010** [comment]
Since `rx.text` is `ControlProperty`, it sends initial value (empy string) when initial subscribe, therefore it sends Reactor.Action.updateTitles to reactor.action . So skip the initial value(empty string) when subscribing.

```
self.titleInput.rx.text.filterNil()
.skip(1)
.map(Reactor.Action.updateTaskTitle)
.bind(to: reactor.action)
.disposed(by: self.disposeBag)
```

**Comment by PierreBrisorgueil** [comment]
Perfect, thank you for this clarification and your time, i did not think about it. (PR on my [Stack / Boilerplate](https://github.com/weareopensource/Swift/pull/60), i will PR here asap to close the issue)
