### ISSUE TITLE
Distinct until changed

### ISSUE THREAD

**Issue by seivan** [devxoul/RxTodo#3]
Why not use `distinctUntilChanged` here https://github.com/devxoul/RxTodo/blob/master/RxTodo/Sources/Rx/RxOperators.swift#L43

The first publish will set, the second won't as it's not distinct.

**Comment by devxoul** [comment]
@seivan, I couldn't understand what you expected. Can you provide me some detail?

**Comment by seivan** [comment]
I'll make a pr as soon as I can. Otherwise ping me in slack.

**Comment by seivan** [comment]
Ah completely slipped my mind. But I can see the code has changed since then.
