### ISSUE TITLE
View doesn't know what ViewModel does. 

### ISSUE THREAD

**Issue by edward-s** [devxoul/RxTodo#8]
Thanks for the excellent project, I've been studying your code and trying to implement it on my own learning project

would like your opinion on this: 
View doesn't know what ViewModel does. View can only communicate to ViewModel about what View did.

I have mixed feelings regarding this.

For example
How is the first code (implemented using your suggestion) more readable than the second code?

``` swift
mailLoginButtonTaps.asObservable()
    .withLatestFrom(Observable.combineLatest(email.asObservable(), password.asObservable()) { ($0, $1) }) .flatMapLatest({ (email, password) in
        return authenticationService.login(withEmail: email, password: password)
            .trackActivity(activityIndicator)
      })
    .asDriver(onErrorJustReturn: false)
```

viewModel.emailLogin()

``` swift
func emailLogin() -> Driver<LoginResult> {
    return authenticationService.login(withEmail: email.value, password: password.value)
            .trackActivity(activityIndicator)
}
```

**Comment by devxoul** [comment]
Why not just:

``` swift
mailLoginButtonTaps.asObservable()
  .flatMap {
    authenticationService.login(withEmail: email.value, password: password.value)
  }
  .asDriver(onErrorJustReturn: false)
```

Also, this is not just for the readability. It's more about responsibility. If using second code, View calls `emailLogin()`, then the View will have a responsibility to handle the `LoginResult` data to map to UI components. This means, View has control flow. This is against the first rule: _View doesn't have control flow. View cannot modify the data. View only knows how to map the data._

With the first code, the whole process of login and the result are handled by ViewModel. Then you can expose the specific data what view need.

**ViewModel**

``` swift
let loggingIn = mailLoginButtonTaps.asObservable()
  .flatMap { in
    authenticationService.login(withEmail: email.value, password: password.value)
  }

self.errorMessageLabelText = loggingIn
  .catchError { error -> Driver<String> in
    Driver.just("\(error)")
  }

self.presentNextViewController = loggingIn
  .flatMap { result in
    return // ...
  }
```

**Comment by edward-s** [comment]
I appreciate your input. I am learning the optimal way to implement MVVM + RxSwift architecture and your sample project has certainly helped.

Firstly,
The reason why I did this

``` swift
.withLatestFrom(Observable.combineLatest(email.asObservable(), password.asObservable()) { ($0, $1) })
```

is that email and password is declared as member variables,

hence if I were to copy+paste your codes, adding the missing required self.:

``` swift
authenticationService.login(withEmail:*self*.email.value, password: *self*.password.value)
```

this will in turn produces a compilation error:  self captured by a closure before all members were initialized.

If I were to move this binding out of the init()

This won't work anymore,

```
self.errorMessageLabelText = loggingIn
```

since errorMessageLabelText has to be initialized in init(), and it requires loggingIn

I'm trying to following your advice for separating responsibilities, however, with all these code jugglings, I ended up with twice the amount of codes and am worried about the long-term readability and maintananibility of the codes.

**Comment by edward-s** [comment]
I'm looking at 2 other MVVM+RxSwift projects which does not seem to enforce this rule strictly.

https://github.com/artsy/eidolon
https://github.com/ivanbruel/SwipeIt

Your thoughts? Or do you know of other open-source projects that managed to implement your coding guidelines successfully?

**Comment by devxoul** [comment]
1. `Variable`s are `class`. You can declare those first than assign to properties:
   
   **ViewModel**
   
   ``` swift
   init() {
     // declare local variables
     let email: Variable<String> = ...
     let password: Variable<String> = ...
   
     // do with local variables
     authenticationService.login(withEmail: email.value, password: password.value)
   
     // assign to properties
     self.email = email
     self.password = password
   }
   ```
2. I understand what you're worrying about. I have same worries too. I'm always thinking and thinking to write a good code. What I think the good code should be is: responsibility-separated, high-readable, long-term-maintainable and easy-testable.
   
   What I wrote in Philosophy section is just a result of my philosophical speculation, and those are closer to 'Guidelines' than the 'Rules'. So please don't be restricted too much in guideline because there are always exceptions in the real world. (The only way to not make exceptions is not to write a code).
   
   PS: I think there're no open sourced apps using my guideline, but I'm developing social media app with these guidelines.
