### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by LeoFangQ** [devxoul/RxTodo#9]
When tap the done button,there is nothing happen

**Comment by devxoul** [comment]
@LeoFangQ, thanks for reporting. I'm gonna check this when I'm available :)

**Comment by wscqs** [comment]
**console:**   [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/mba/Library/Developer/CoreSimulator/Devices/3170CF8B-96BB-4E52-80CA-02B740792536/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
[MC] Reading from private effective user settings.

**Bug:**   Operation, cannot update/delete/save operation

**Comment by devxoul** [comment]
This is fixed in recent commits.
